[package]
name = "finances"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "1"
argon2 = { version = "0.5", features = ["std"] }
rusqlite = { version = "0.40.2", features = ["bundled"] }
axum = "0.8.9"
tokio = { version = "1.53.1", features = ["full"] }
serde = { version = "1.0.229", features = ["derive"] }
uuid = { version = "1.24.0", features = ["v4"] }
